name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        I'd love to hear your ideas. Describe the problem you're running into and what you think would help.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What are you trying to do? What's frustrating about the current experience?
      placeholder: "I often need to ... but currently I have to ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work? Be as specific as you want.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you tried any workarounds? Are there other approaches you've considered?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, links to similar features in other tools, etc.
    validations:
      required: false
